title: Comp-sci-tools
email: gosia.olejniczak@gmail.com
description: >-
  We meet and discuss the best practices in computational sciences.
url: "https://comp-sci-tools.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github: "https://github.com/comp-sci-tools/comp-sci-tools.github.io" 

theme: minima
plugins:
  - jekyll-feed

include:
  - _pages
