title: Comp-sci-tools workshops
email: gosia.olejniczak@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  We meet and discuss the best practices in computational sciences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://comp-sci-tools.github.io/index.html" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
theme: minima
plugins:
  - jekyll-feed

